name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goVer: ["1.21.x"]

    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Format
        run: diff -u <(echo -n) <(gofmt -d .)

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go get gopkg.in/check.v1

      - name: Build
        run: go build -v ./...
